apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB:       # database name
  POSTGRES_USER:     # database user name
  POSTGRES_PASSWORD: # database password
