apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: user-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image: kiwib0y/user-demo:latest
        ports:
        - containerPort: 3000
        env:
        - name: PG_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: PG_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: PG_HOST
          value: "postgres.pg-database.svc.cluster.local" # Full DNS for PostgreSQL service
        - name: PG_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo
spec:
  selector:
    app: app-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
